//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Igor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorization
    {
        public Authorization()
        {
            this.Person = new HashSet<Person>();
        }
    
        public short Code { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<short> CodePerson { get; set; }
    
        public virtual ICollection<Person> Person { get; set; }
    }
}
