//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Igor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public short CodePerson { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Position { get; set; }
        public Nullable<short> CodeAuthorization { get; set; }
    
        public virtual Authorization Authorization { get; set; }
    }
}
